# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/student_placement_readiness
spring.datasource.username=postgres
spring.datasource.password=realestate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

